#!/usr/bin/env python3
"""
Helper script to generate mentor IDs mapping file

This script can be used in two ways:
1. Parse output from upload_and_accept_mentors script to extract mentor IDs
2. Fetch mentor IDs from the backend API by email lookup

This creates a file with format: Mentor Name|mentor_id
"""

import json
import os
import sys
import re
from pathlib import Path
import requests


def generate_from_api(api_base, api_key, json_file, output_file):
    """Fetch mentor IDs from API by looking up each mentor"""
    print("🔍 Fetching mentor IDs from API...")
    
    with open(json_file, 'r') as f:
        mentors = json.load(f)
    
    headers = {
        'accept': '*/*',
        'X-API-KEY': api_key
    }
    
    mapping = []
    found_count = 0
    not_found_count = 0
    
    for mentor in mentors:
        mentor_name = mentor.get('fullName', 'Unknown')
        mentor_email = mentor.get('email', '')
        
        print(f"  Searching for: {mentor_name}...", end=' ')
        
        try:
            # Try to fetch mentor by email or other identifier
            # This is a placeholder - actual API endpoint may vary
            # You may need to list all mentors and match by name/email
            response = requests.get(
                f"{api_base}/platform/v1/mentors",
                headers=headers,
                timeout=10
            )
            
            if response.status_code == 200:
                all_mentors = response.json()
                # Try to find this mentor in the list
                found = False
                for api_mentor in all_mentors:
                    if (api_mentor.get('email') == mentor_email or 
                        api_mentor.get('fullName') == mentor_name):
                        mentor_id = api_mentor.get('id')
                        if mentor_id:
                            mapping.append(f"{mentor_name}|{mentor_id}")
                            print(f"✅ Found (ID: {mentor_id})")
                            found_count += 1
                            found = True
                            break
                
                if not found:
                    print("⚠️  Not found")
                    not_found_count += 1
            else:
                print(f"❌ API error: {response.status_code}")
                not_found_count += 1
        
        except Exception as e:
            print(f"❌ Error: {str(e)}")
            not_found_count += 1
    
    # Write mapping file
    with open(output_file, 'w') as f:
        f.write("# Mentor Name to ID Mapping\n")
        f.write("# Format: Mentor Full Name|mentor_id\n")
        f.write("# Generated by generate_mentor_ids_mapping.py\n\n")
        for line in mapping:
            f.write(line + '\n')
    
    print()
    print(f"✅ Mapping file created: {output_file}")
    print(f"   Found: {found_count}")
    print(f"   Not found: {not_found_count}")
    
    return found_count > 0


def generate_template(json_file, output_file):
    """Generate a template mapping file with mentor names"""
    print("📝 Generating template mapping file...")
    
    with open(json_file, 'r') as f:
        mentors = json.load(f)
    
    with open(output_file, 'w') as f:
        f.write("# Mentor Name to ID Mapping Template\n")
        f.write("# Format: Mentor Full Name|mentor_id\n")
        f.write("# Please fill in the mentor IDs after running upload_and_accept_mentors script\n\n")
        
        for mentor in mentors:
            mentor_name = mentor.get('fullName', 'Unknown')
            f.write(f"{mentor_name}|FILL_IN_ID_HERE\n")
    
    print(f"✅ Template file created: {output_file}")
    print(f"   Total mentors: {len(mentors)}")
    print()
    print("Next steps:")
    print("  1. Run the upload_and_accept_mentors script")
    print("  2. Note down the mentor IDs from the output")
    print("  3. Fill them in the template file")
    print("  4. Use the filled file with upload_mentor_pictures script")


def main():
    script_dir = Path(__file__).parent
    json_file = script_dir / '..' / 'mentor_json_outputs' / 'longterm_or_both_mentors.json'
    output_file = script_dir / 'mentor_ids_mapping.txt'
    
    api_base = os.getenv('API_BASE', 'https://wcc-backend-prod.fly.dev/api')
    api_key = os.getenv('API_KEY', '')
    
    print("🚀 Mentor IDs Mapping Generator")
    print()
    
    if not json_file.exists():
        print(f"❌ Error: JSON file not found: {json_file}")
        sys.exit(1)
    
    # Check command line arguments
    if len(sys.argv) > 1 and sys.argv[1] == '--template':
        generate_template(json_file, output_file)
    elif api_key:
        # Try to fetch from API
        if generate_from_api(api_base, api_key, json_file, output_file):
            print()
            print("You can now use this mapping file:")
            print(f"  MENTOR_IDS_FILE={output_file} ./upload_mentor_pictures.sh")
        else:
            print()
            print("⚠️  Could not fetch all mentor IDs from API.")
            print("You may need to generate a template and fill it manually:")
            print(f"  python3 {__file__} --template")
    else:
        print("Usage:")
        print(f"  1. Generate template: python3 {__file__} --template")
        print(f"  2. Fetch from API:    API_KEY='your-key' python3 {__file__}")
        print()
        print("Generating template by default...")
        print()
        generate_template(json_file, output_file)


if __name__ == '__main__':
    main()
